// **** AUTOMATICALLY GENERATED BY mk-visitor-decls.pl -- DO NOT EDIT ****
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__

#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__

  virtual void do_address_of_node(m19::address_of_node *const node, int lvl) = 0;
  virtual void do_block_node(m19::block_node *const node, int lvl) = 0;
  virtual void do_body_node(m19::body_node *const node, int lvl) = 0;
  virtual void do_break_node(m19::break_node *const node, int lvl) = 0;
  virtual void do_continue_node(m19::continue_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(m19::evaluation_node *const node, int lvl) = 0;
  virtual void do_final_section_node(m19::final_section_node *const node, int lvl) = 0;
  virtual void do_function_call_node(m19::function_call_node *const node, int lvl) = 0;
  virtual void do_function_declaration_node(m19::function_declaration_node *const node, int lvl) = 0;
  virtual void do_function_definition_node(m19::function_definition_node *const node, int lvl) = 0;
  virtual void do_identity_node(m19::identity_node *const node, int lvl) = 0;
  virtual void do_if_else_node(m19::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(m19::if_node *const node, int lvl) = 0;
  virtual void do_indexing_node(m19::indexing_node *const node, int lvl) = 0;
  virtual void do_initial_section_node(m19::initial_section_node *const node, int lvl) = 0;
  virtual void do_memory_alloc_node(m19::memory_alloc_node *const node, int lvl) = 0;
  virtual void do_print_node(m19::print_node *const node, int lvl) = 0;
  virtual void do_read_node(m19::read_node *const node, int lvl) = 0;
  virtual void do_return_node(m19::return_node *const node, int lvl) = 0;
  virtual void do_section_node(m19::section_node *const node, int lvl) = 0;
  virtual void do_for_node(m19::for_node *const node, int lvl) = 0;
  virtual void do_variable_declaration_node(m19::variable_declaration_node *const node, int lvl) = 0;
  virtual void do_apply_node(m19::apply_node *const node, int lvl) = 0;


#else

  void do_address_of_node(m19::address_of_node *const node, int lvl);
  void do_block_node(m19::block_node *const node, int lvl);
  void do_body_node(m19::body_node *const node, int lvl);
  void do_break_node(m19::break_node *const node, int lvl);
  void do_continue_node(m19::continue_node *const node, int lvl);
  void do_evaluation_node(m19::evaluation_node *const node, int lvl);
  void do_final_section_node(m19::final_section_node *const node, int lvl);
  void do_function_call_node(m19::function_call_node *const node, int lvl);
  void do_function_declaration_node(m19::function_declaration_node *const node, int lvl);
  void do_function_definition_node(m19::function_definition_node *const node, int lvl);
  void do_identity_node(m19::identity_node *const node, int lvl);
  void do_if_else_node(m19::if_else_node *const node, int lvl);
  void do_if_node(m19::if_node *const node, int lvl);
  void do_indexing_node(m19::indexing_node *const node, int lvl);
  void do_initial_section_node(m19::initial_section_node *const node, int lvl);
  void do_memory_alloc_node(m19::memory_alloc_node *const node, int lvl);
  void do_print_node(m19::print_node *const node, int lvl);
  void do_read_node(m19::read_node *const node, int lvl);
  void do_return_node(m19::return_node *const node, int lvl);
  void do_section_node(m19::section_node *const node, int lvl);
  void do_for_node(m19::for_node *const node, int lvl);
  void do_variable_declaration_node(m19::variable_declaration_node *const node, int lvl);
  void do_apply_node(m19::apply_node *const node, int lvl);


#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */

#endif /* __IN_VISITOR_HEADER__ */
